/**
 * Action Types
 */
export const LOAD_BLOG_POSTS = 'LOAD_BLOG_POSTS';
export const ADD_BLOG_POST = 'ADD_BLOG_POST';

export const LOAD_PROJECTS = 'LOAD_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';

export const LOAD_LEARNING_BOOKS = 'LOAD_LEARNING_BOOKS';
export const ADD_LEARNING_BOOK = 'ADD_LEARNING_BOOK';

export const LOAD_LEARNING_SCHOOLS = 'LOAD_LEARNING_SCHOOLS';
export const ADD_LEARNING_SCHOOL = 'ADD_LEARNING_SCHOOL';

export const LOAD_LEARNING_COURSES = 'LOAD_LEARNING_COURSES';
export const ADD_LEARNING_COURSE = 'ADD_LEARNING_COURSE';

export const LOAD_LEARNING_QUOTES = 'LOAD_LEARNING_QUOTES';
export const ADD_LEARNING_QUOTE = 'ADD_LEARNING_QUOTE';

export const LOAD_SLIDERS = 'LOAD_SLIDERS';
export const ADD_SLIDER = 'ADD_SLIDER'

export const LOAD_TAGS = 'LOAD_TAGS';
export const ADD_TAG = 'ADD_TAG';

export const LOAD_TECHNOLOGIES = 'LOAD_TECHNOLOGIES';

export const LOAD_ABOUT_SLIDERS = 'LOAD_ABOUT_SLIDERS';
export const ADD_ABOUT_SLIDER = 'ADD_ABOUT_SLIDER';